- .eslintrc.cjs
- .husky/commit-msg
- .husky/pre-commit
- commitlint.config.js
- lint-staged.config.js
- package.json
- pnpm-lock.yaml
- tsconfig.json
feat: install husky
feat: set up pre-commit hook
feat: set-up commitlint
chore: re-sort eslintrc
> feat: install husky and set-up commit hooks

- app/layout.tsx
- components/theme-provider.tsx
- components/theme-provider/index.tsx
- components/theme-provider/next-themes-provider.tsx
- components/theme-provider/radix-themes.provider.tsx
- package.json
- pnpm-lock.yaml
feat: install next-themes
feat: init theme-provider
> feat: install next-themes

- app/(auth)/auth/sign-in/route.ts
- lib/services/spotify/client.ts
- lib/services/spotify/get-user-shows.ts
- package.json
- pnpm-lock.yaml
feat: implement get user shows service
chore: change types of search user shows function return
> feat: implement get user shows service

- lib/errors.ts
- package.json
- pnpm-lock.yaml
Introduces our identifiable errors within so we can track them down gracefully.
> feat: add extendable errors with es6-error

- env.mjs
- package.json
- pnpm-lock.yaml
@okanisildar will rebase and merge this after we're done with all the other PRs since this will break their env usage.
> feat: use t3-oss/next-env for env validation

- components/layout/app-header.stories.tsx
- components/layout/app-header.tsx
- components/layout/app-layout.tsx
- components/theme-provider/styles.css
- chore: use inline await in if
- chore: update `menu-item` cursor
- feat: add real links to app-header
> feat: add links to `user-menu`

- app/(dashboard)/layout.tsx
> feat: add basic layout for dashboard

- components/episode-card.module.css
- components/episode-card.stories.tsx
- components/episode-card.tsx
- package.json
- pnpm-lock.yaml
(had to modify it a little bit in the show details page PR.)
https://github.com/experiment-station/beecast/assets/9790196/935fb51c-bc06-4455-a2ae-6ec745e11d9f
> feat: add `episode-card` component

- app/(dashboard)/shows/[id]/page.tsx
- components/episode-card.module.css
- components/episode-card.stories.tsx
- components/episode-card.tsx
- package.json
- pnpm-lock.yaml
> feat: `shows/:id` page [SUPA-11]

- app/@modal/(.)episodes/[id]/page.tsx
- app/episodes/[id]/page.tsx
- app/episodes/layout.tsx
- app/shows/[id]/page.tsx
- app/shows/page.tsx
- components/episode-card.tsx
- components/episode-detail.stories.tsx
- components/episode-detail.tsx
- components/layout/app-content.tsx
- components/route-modal.tsx
- components/ui/decorative-box.module.css
- components/ui/decorative-box.tsx
https://github.com/experiment-station/beecast/assets/9790196/911974e5-6ff4-462a-9c43-53f47ed6524c
> feat: init `episodes/:id` route [SUPA-12]

- app/shows/[id]/page.tsx
- components/show-card.tsx
> refactor: use `Avatar` for show images

- components/ui/client-only.tsx
- components/ui/collapsible-panel.module.css
- components/ui/collapsible-panel.stories.tsx
- components/ui/collapsible-panel.tsx
- lib/fixtures/fake-episode-summary.tsx
thinking of using this for the episode description and summaries.
https://github.com/experiment-station/beecast/assets/9790196/00f63009-88db-43c3-a9e7-14d4309ebcc1
> feat: add collapsible panel component

- components/episode-card.module.css
- components/episode-card.tsx
- components/episode-description.module.css
- components/episode-description.tsx
- components/show-card.module.css
- components/show-card.tsx
- components/ui/line-clamp.module.css
- components/ui/line-clamp.tsx
> refactor: modularize `show-card` and `episode-card`

- components/episode-card.tsx
- components/layout/app-footer.tsx
- components/layout/app-header.tsx
spent too much time in Linear's website last nite, made stuff smaller in general 🧑‍🎨
> refactor: minor design tweaks

- app/shows/[id]/page.tsx
- components/episode-card.stories.tsx
- components/episode-card.tsx
https://github.com/experiment-station/beecast/assets/9790196/27df25b2-c04d-4794-9e18-02180a2e179f
> feat: add `ai` badge to `episode-card`

- app/(home)/page.tsx
- components/theme-provider/radix-themes.provider.tsx
- components/ui/browser-frame.css
- components/ui/browser-frame.module.css
- components/ui/browser-frame.tsx
- package.json
- pnpm-lock.yaml
> feat: init landing page

- app/credits/components/credit-list-item.tsx
- app/credits/layout.tsx
- app/credits/page.tsx
- package.json
- pnpm-lock.yaml
> feat: add `credits` page

- lib/services/ai/deepgram.ts
- lib/services/ai/transcribe-episode.ts
- lib/utils/get-final-redirect-url.ts
feat: add `get-final-redirect-url` to fix deepgram redirections
refactor: throw deepgram errors
> feat: add `get-final-redirect-url` to fix deepgram redirections - [SUPA-45]

- app/shows/page.tsx
> feat: add your shows to shows page

- app/shows/page.tsx
- components/select-shows.tsx
- components/show-card.module.css
- components/show-card.stories.tsx
- components/show-card.tsx
> refactor: spotifize `show-card`

- lib/services/ai/deepgram.ts
- lib/services/ai/transcribe-episode.ts
> feat: support non-english languages for `transcriptions`

- app/api/ai/summarize/[episode-id]/route.ts
- components/episode-ai-summary/episode-ai-summary-streamer.tsx
- lib/services/ai/create-episode-summary-stream.ts
- package.json
- pnpm-lock.yaml
https://github.com/experiment-station/beecast/assets/9790196/b9123628-0d17-46b0-be6e-d7fa8a326cbc
> feat: choose open-ai modal based on tokens

- app/(home)/page.tsx
- components/audio-player.stories.tsx
- components/audio-player.tsx
- components/episode-detail.tsx
very basic audio player in episode detail page until we have something more complicated.
https://github.com/experiment-station/beecast/assets/27828319/fbe2a847-fedb-4f42-b09c-fb056e8a39c0
> feat: basic audio player
